# Generated by Django 5.1.5 on 2025-02-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Ім'я")),
                ('access_level', models.CharField(choices=[('super', 'Супер'), ('admin', 'Адміністратор'), ('delivery', 'Доставник')], default='admin', max_length=12, verbose_name='Рівень доступу')),
                ('user_id', models.CharField(max_length=100, unique=True, verbose_name='ID користувача')),
            ],
        ),
    ]
