# Generated by Django 5.1.5 on 2025-05-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Ім'я")),
                ('login', models.CharField(max_length=20, unique=True, verbose_name='Логін')),
                ('password', models.CharField(default='0000', max_length=128, verbose_name='Пароль')),
                ('access_level', models.CharField(choices=[('super', 'Супер'), ('admin', 'Адміністратор'), ('worker', 'Оператор виготовлення')], default='admin', max_length=12, verbose_name='Рівень доступу')),
                ('user_id', models.CharField(max_length=100, unique=True, verbose_name='ID користувача')),
            ],
        ),
    ]
