# Generated by Django 5.1.5 on 2025-05-27 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва виду витрат')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20, verbose_name='Місяць')),
                ('leads', models.PositiveIntegerField(verbose_name='Ліди')),
                ('conversions', models.PositiveIntegerField(verbose_name='Конверсії')),
                ('sales_plan', models.PositiveIntegerField(verbose_name='План продажу')),
                ('planned_budget', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Планований бюджет')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Опис')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума')),
                ('expense_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.expensetype', verbose_name='Вид витрат')),
            ],
        ),
    ]
