# Generated by Django 5.1.5 on 2025-01-21 10:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва пропозиції')),
                ('description', models.TextField(max_length=760, verbose_name='Опис')),
                ('size_of_foot', models.IntegerField(default=45, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(70)], verbose_name='Розмір ноги')),
                ('width', models.IntegerField(default=45, validators=[django.core.validators.MinValueValidator(20)], verbose_name='Довжина')),
                ('length', models.IntegerField(default=45, validators=[django.core.validators.MinValueValidator(20)], verbose_name='Ширина')),
                ('weight', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Вага')),
                ('materials', models.TextField(max_length=100, verbose_name='Матеріали')),
                ('equipment', models.TextField(max_length=100, verbose_name='Комплектація')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Ціна')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Ціна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Зображення')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
        ),
    ]
