# Generated by Django 5.1.5 on 2025-05-27 15:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('surname', models.CharField(max_length=100, verbose_name='Прізвище')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
            ],
        ),
        migrations.CreateModel(
            name='Engraving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_id', models.PositiveIntegerField(default=0, unique=True, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Назва')),
                ('image', models.ImageField(upload_to='graws/', verbose_name='Гравіювання')),
                ('upload_at', models.DateField(auto_now_add=True, null=True, verbose_name='Завантажено')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва пропозиції')),
                ('engraving', models.BooleanField(default=False, verbose_name='Можливість обрати гравіювання')),
                ('description', models.TextField(max_length=760, verbose_name='Опис')),
                ('size_of_foot', models.IntegerField(default=45, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(70)], verbose_name='Розмір ноги')),
                ('step', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(50)], verbose_name='Крок')),
                ('width', models.IntegerField(default=35, validators=[django.core.validators.MinValueValidator(20)], verbose_name='Довжина')),
                ('length', models.IntegerField(default=14, validators=[django.core.validators.MinValueValidator(14)], verbose_name='Ширина')),
                ('weight', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Вага')),
                ('materials', models.TextField(max_length=100, verbose_name='Матеріали')),
                ('equipment', models.TextField(max_length=100, verbose_name='Комплектація')),
                ('price', models.DecimalField(decimal_places=0, max_digits=11, verbose_name='Ціна')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=0, max_digits=11, null=True, verbose_name='Акційна ціна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Дата відправки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний на сайті')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, verbose_name='Населений пункт')),
                ('post', models.CharField(max_length=50, verbose_name='Відділення пошти')),
                ('quantity', models.DecimalField(decimal_places=0, max_digits=2, verbose_name='Кількість')),
                ('comment', models.TextField(blank=True, max_length=400, null=True, verbose_name='Коментар')),
                ('price', models.DecimalField(decimal_places=0, max_digits=11, verbose_name='Ціна заомвлення')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата замовлення')),
                ('status', models.CharField(choices=[('received', 'Отримана'), ('sent', 'Відправленна'), ('wait', 'Чекає відправлення'), ('production', 'Виготовлення'), ('should_call', 'Уточнення')], default='production', max_length=50, verbose_name='Статус')),
                ('customer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.customer', verbose_name='ID замовника')),
                ('engraving', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.engraving', verbose_name='ID гравіювання')),
                ('manager_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.systemuser', verbose_name='ID менеджера')),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product', verbose_name='ID товару')),
            ],
        ),
        migrations.CreateModel(
            name='Available',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.DecimalField(decimal_places=0, max_digits=2, verbose_name='Кількість')),
                ('comment', models.CharField(max_length=300, verbose_name='Коментар')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Cтворено')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Зображення')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
        ),
    ]
