# Generated by Django 5.1.5 on 2025-05-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Дата відправлення'),
        ),
    ]
