# Generated by Django 5.1.5 on 2025-02-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_sale_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255, verbose_name='Назва пропозиції')),
                ('name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('surname', models.CharField(max_length=100, verbose_name='Прізвище')),
                ('phone', models.CharField(max_length=50, verbose_name='Номер телефону')),
                ('address', models.CharField(max_length=100, verbose_name='Населений пункт')),
                ('post', models.CharField(max_length=50, verbose_name='Відділення пошти')),
                ('engraving', models.CharField(max_length=50, verbose_name='Грвіювання')),
                ('quantity', models.DecimalField(decimal_places=0, max_digits=2, verbose_name='Кількість')),
                ('manager', models.BooleanField(default=True, verbose_name='Необхідно зателефонувати')),
                ('comment', models.TextField(max_length=400, verbose_name='Коментар')),
                ('price', models.DecimalField(decimal_places=0, max_digits=11, verbose_name='Ціна заомвлення')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата замовлення')),
            ],
        ),
    ]
