# Generated by Django 5.1.5 on 2025-02-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_order_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sent',
            field=models.BooleanField(default=False, verbose_name='Відправлена'),
        ),
    ]
