# Generated by Django 5.1.5 on 2025-02-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_order_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='engraving',
            field=models.BooleanField(default=False, verbose_name='Можливість обрати гравіювання'),
        ),
        migrations.AlterField(
            model_name='order',
            name='engraving',
            field=models.CharField(default=None, max_length=50, verbose_name='Грвіювання'),
        ),
    ]
