# Generated by Django 5.1.5 on 2025-02-04 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_engraving_alter_order_engraving'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engraving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('image', models.ImageField(upload_to='graws/', verbose_name='Гравіювання')),
            ],
        ),
    ]
