# Generated by Django 5.1.5 on 2025-02-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_engraving_upload_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engraving',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Назва'),
        ),
    ]
