# Generated by Django 5.1.5 on 2025-02-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_engraving_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engraving',
            name='upload_at',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Завантажено'),
        ),
    ]
