# Generated by Django 5.1.5 on 2025-01-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselimage',
            name='button',
            field=models.CharField(max_length=200, verbose_name='Текст кнопки'),
        ),
    ]
