# Generated by Django 5.1.5 on 2025-01-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_carouselimage_button'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselimage',
            name='slide_type',
            field=models.CharField(choices=[('#catalog', 'Каталог'), ('#about-sadhu', 'Про садху'), ('#about-us', 'Про нас')], default='#catalog', max_length=12, verbose_name='Тип слайду'),
        ),
    ]
